// LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

// LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILURE = "LOGOUT_FAILURE"

// CLEAR ERROR
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST"
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS"
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE"

// REGISTER
export const REGIST_REQUEST = "REGIST_REQUEST"
export const REGIST_SUCCESS = "REGIST_SUCCESS"
export const REGIST_FAILURE = "REGIST_FAILURE"

// USER LOADING
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST"
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS"
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE"